<?php

function foo_menu() {
  $items = array();
  $items['foo/form'] = array(
    'title' => t('My form'),
    'page callback' => 'foo_form',
    'access arguments' => array('access content'),
    'description' => t('My form'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function foo_form() {
  return drupal_get_form('foo_my_form');
}

function foo_my_form($form_state) {
  // Normally wouldn't do this; but the function is simple enough
  // @todo remove later and place as external file
  drupal_add_js('jQuery(document).ready(function () {
      jQuery("#edit-override").click(function () {
        var text = window.prompt("Please provide text to replace in the input field","");
        jQuery("#edit-message").val(text);
      });
    });',
    array('type' => 'inline', 'scope' => 'footer', 'weight' => 5)
  );
  $form['message'] = array(
    '#type' => 'textfield',
    '#title' => t('My message!'),
    '#required' => TRUE,
    '#default_value' => "First name",
    '#description' => "Please enter your message you'd like to set",
    '#size' => 20,
    '#maxlength' => 20,
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );
  $form['override'] = array(
    '#type' => 'button',
    '#value' => 'Override',
    '#attributes' => array(
      'onclick' => 'return false;',
    ),
  );
  return $form;
}

function foo_my_form_validate($form, &$form_state) {
}

// Adds a submit handler/function to our form to send a successful
// completion message to the screen.


function foo_my_form_submit($form, &$form_state) {
  $output = check_plain($form['message']['#value']);
  drupal_set_message($output);
}
